name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly App
        run: |
          dotnet publish Check.Web/Check.Web.csproj -c Release -o build_output \
            -p:PublishTrimmed=false \
            -p:PublishSingleFile=false \
            -p:BlazorEnableCompression=true \
            -p:BlazorWebAssemblyLoadAllGlobalizationData=true \
            -p:StaticWebAssetBasePath=Check \
            -p:BasePath=/Check/
      - name: List contents of build_output
        run: |
            echo "::group::build_output"
            ls -R build_output
            echo "::endgroup::"

      - name: Copy index.html to 404.html
        run: |
          cp build_output/wwwroot/Check/index.html build_output/wwwroot/Check/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build_output/wwwroot
          user_name: Ivan Patricio
          user_email: ivan.patricio.quispe@gmail.com