name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repo
        uses: actions/checkout@v3

      - name: Instala .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publica la app
        run: dotnet publish Check.Web/Check.Web.csproj -c Release -o dist /p:StaticWebAssetBasePath=Check

      - name: Sube a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist/wwwroot
          user_name: Ivan Patricio
          user_email: ivan.patricio.quispe@gmail.com
          clean: true