name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Check.sln

      - name: Build
        run: dotnet build Check.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Check.Web/Check.Web.csproj -c Release -o release --nologo

      - name: Prepare artifact
        run: |
          mkdir -p public/Check
          cp -r Check.Web/bin/Release/net8.0/browser-wasm/publish/wwwroot/* public/Check/
          touch public/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./Check
          user_name: Ivan Patricio
          user_email: ivan.patricio.quispe@gmail.com