name: Publish to GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Check.sln

    - name: Build
      run: dotnet build Check.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Check.Web/Check.Web.csproj -c Release -o release --nologo

    - name: Prepare artifact
      run: |
        mkdir -p docs
        cp -r Check.Web/bin/Release/net8.0/browser-wasm/publish/wwwroot/* docs/
        touch docs/.nojekyll
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: public
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./Check
          user_name: Ivan Patricio
          user_email: ivan.patricio.quispe@gmail.com